[window]
title = "tty"
dynamic_title = false

[env]
TERM_PROGRAM = "Alacritty"
WSLENV = "TERM/u:COLORTERM/u:TERM_PROGRAM/u"

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[cursor.style]
shape = "Block"
blinking = "Never"

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "WheelUp", mods = "Control | Shift", action = "IncreaseFontSize" },
  { mouse = "WheelDown", mods = "Control | Shift", action = "DecreaseFontSize" },
]

[terminal]
shell = { program = "wsl.exe", args = ["--cd", "~"] }

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[keyboard]
bindings = [
  { key = "Backspace", mods = "Control", chars = "\u0017" },
  { key = "Space", mods = "Control", chars = "\u0000" },
  { key = "Space", mods = "Control | Alt", chars = "\u001b\u0000" },
  { key = 20, mods = "Control | Alt", chars = "\u001b\u0014" },
  { key = 35, mods = "Control | Alt", chars = "\u001b\u0008" },
  { key = 36, mods = "Control | Alt", chars = "\u001b\u000a" },
  { key = 37, mods = "Control | Alt", chars = "\u001b\u000b" },
  { key = 38, mods = "Control | Alt", chars = "\u001b\u000c" },
  { key = 34, mods = "Control | Alt", chars = "\u001b\u0007" },
  { key = 49, mods = "Control | Alt", chars = "\u001b\u000e" },
  { key = 21, mods = "Control | Alt", chars = "\u001b\u0019" },
  # This must precede the Ctrl+Alt+S physical-key binding below.
  { key = 31, mods = "Control | Alt | Shift", chars = "\u001b[994~" },
  { key = 31, mods = "Control | Alt", chars = "\u001b\u0013" },
  { key = 48, mods = "Control | Alt", chars = "\u001b\u0002" },
  { key = 16, mods = "Control | Alt", chars = "\u001b\u0011" },
  { key = 30, mods = "Control | Alt", chars = "\u001b\u0001" },
  { key = 24, mods = "Control | Alt", chars = "\u001b\u000f" },
  { key = 44, mods = "Control | Alt", chars = "\u001b\u001a" },
  { key = "F11", action = "ToggleFullscreen" },
  { key = 43, mods = "Control | Alt", chars = "\u001b\u001c" },
  { key = "C", mods = "Control | Shift", action = "Copy" },
  { key = "V", mods = "Control", action = "Paste" },
  { key = 26, mods = "Control | Alt", chars = "\u001b[991~" },
  { key = 27, mods = "Control | Alt", chars = "\u001b[992~" },
  { key = "S", mods = "Control | Shift", chars = "\u001b[993~" },
  { key = "Enter", mods = "Shift", chars = "\u001b\r" },
]
