vim.cmd [[ au colorscheme * hi Normal guibg=NONE ctermbg=NONE ]]
vim.cmd [[ au colorscheme * hi Terminal guibg=NONE ctermbg=NONE ]]
vim.cmd [[ au colorscheme * hi LineNr guibg=NONE ctermbg=NONE ]]
vim.cmd [[ au colorscheme * hi CursorLineNR guibg=NONE ctermbg=NONE ]]
vim.cmd [[ au colorscheme * hi SignColumn guibg=NONE ctermbg=NONE ]]
vim.cmd [[ au colorscheme * hi FoldColumn guibg=NONE ctermbg=NONE ]]
vim.cmd [[ au colorscheme * hi VertSplit guibg=NONE ctermbg=NONE ]]
vim.cmd [[ au colorscheme * hi Folded guibg=NONE ctermbg=NONE ]]
vim.cmd [[ au colorscheme * hi NonText guibg=NONE ctermbg=NONE guifg=#83a598 ]]
vim.cmd [[ au colorscheme * hi SpecialKey guibg=NONE ctermbg=NONE ]]
vim.cmd [[ au colorscheme * hi StatusLine guifg=#3c3836 ]]
vim.cmd [[ au colorscheme * hi EndOfBuffer guibg=NONE ctermbg=NONE guifg=#504945 ]]
vim.cmd [[ au colorscheme * hi WarningMsg guibg=NONE ctermbg=NONE guifg=#fb4934 ]]
vim.cmd [[ au colorscheme * hi DiagnosticError guifg=#fb4934 ]]
vim.cmd [[ au colorscheme * hi GitSignsAdd guibg=NONE ctermbg=NONE guifg=#989719 "#b16286 ]]
vim.cmd [[ au colorscheme * hi GitSignsChange guibg=NONE ctermbg=NONE guifg=#448488 ]]
vim.cmd [[ au colorscheme * hi GitSignsDelete guibg=NONE ctermbg=NONE guifg=#fb4934 ]]
vim.cmd [[ au colorscheme * hi NvimTreeIndentMarker guifg=#504945 ]]
vim.cmd [[ au colorscheme * hi NormalFloat guibg=NONE ctermbg=NONE ]]
vim.cmd [[ au colorscheme * hi IndentBlanklineChar guifg=#504945 gui=nocombine ]]
vim.cmd [[ au colorscheme * hi IndentBlanklineSpaceChar guifg=#504945 gui=nocombine ]]
vim.cmd [[ au colorscheme * hi IndentBlanklineSpaceCharBlankline guifg=#504945 gui=nocombine ]]
vim.cmd [[ au colorscheme * hi IndentBlanklineContextChar guifg=#504945 gui=nocombine ]]
vim.cmd [[ au colorscheme * hi CmpItemMenu guifg=#a89984 gui=nocombine ]]

vim.cmd [[ let g:gruvbox_contrast_dark = 'hard' ]]
vim.cmd [[ let g:gruvbox_invert_selection = '0' ]]

vim.cmd [[ silent! colorscheme gruvbox ]]

