let $VC = $HOME . '/.files/vim'
let $NVC = $HOME . '/.config/nvim'

source $VC/settings.vim
source $VC/plugins.vim
source $VC/functions.vim
source $VC/theme.vim
source $VC/mappings.vim
source $VC/filetypes.vim

" plugin configs
source $VC/plugc/gitgutter.vim
source $VC/plugc/vimwiki.vim
source $VC/plugc/indentline.vim
source $VC/plugc/sneak.vim
source $VC/plugc/netrw.vim
source $VC/plugc/fern.vim
source $VC/plugc/autopairs.vim
source $VC/plugc/neoterm.vim
source $VC/plugc/startify.vim
source $VC/plugc/codi.vim
source $VC/plugc/vsnip.vim
source $VC/plugc/vimqf.vim
source $VC/plugc/text-objects.vim
source $VC/plugc/myvis.vim

if has('nvim-0.5') && !exists('g:vscode')
  luafile $VC/lspconfig.lua
  luafile $VC/plugc/treesitter.lua
  luafile $VC/plugc/nvim-compe.lua
  luafile $VC/plugc/trouble.lua
  luafile $VC/plugc/formatter.lua
  luafile $VC/plugc/lsp_signature.lua
  luafile $VC/plugc/rust_tools.lua
  luafile $VC/plugc/todo_comments.lua
  luafile $VC/plugc/telescope.lua
  luafile $VC/plugc/bufferline.lua
  luafile $VC/plugc/lualine.lua
  lua require'colorizer'.setup()
  lua require'which-key'.setup()
endif

