let $VC = $HOME . '/.files/vim'
let $NVC = $HOME . '/.config/nvim'

source $VC/settings.vim
source $VC/plugins.vim
source $VC/functions.vim
source $VC/theme.vim
source $VC/mappings.vim
source $VC/filetypes.vim

" plugin configs
source $VC/plugc/nvim-lsp.vim
source $VC/plugc/nvim-compe.vim
source $VC/plugc/gitgutter.vim
source $VC/plugc/fzf.vim
source $VC/plugc/vimwiki.vim
source $VC/plugc/indentline.vim
source $VC/plugc/sneak.vim
source $VC/plugc/netrw.vim
source $VC/plugc/fern.vim
source $VC/plugc/autopairs.vim
source $VC/plugc/neoterm.vim
source $VC/plugc/startify.vim
source $VC/plugc/whichkey.vim
source $VC/plugc/fzfproject.vim
source $VC/plugc/fzfcheckout.vim
source $VC/plugc/codi.vim
source $VC/plugc/vsnip.vim
source $VC/plugc/vimqf.vim
source $VC/plugc/text-objects.vim

