#!/bin/bash

executable="$(echo | dmenu -fn "Fira Code Retina:size=12" -nb rgb:eb/db/b2 -nf rgb:20/20/20 -sb rgb:eb/db/b2 -sf rgb:eb/db/b2)"
if [[ $executable != "" ]]; then kitty bash -ic $executable; fi
exit 0

