#!/usr/bin/env bash

kitty_win_id=$(wmctrl -l | awk '/kitty-float/ {print $1}')
active=$(xdotool getactivewindow getwindowname)

if [ -z $kitty_win_id ]; then
  kitty --title kitty-float --override background_opacity=0.9  
elif [ $active == "kitty-float" ]; then
  wmctrl -r $active -b toggle,hidden
else
  echo $kitty_win_id | xargs wmctrl -iR
fi
