add_newline =	true

format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$package\
$env_var\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

[character]
success_symbol = "[⮞](9)"
error_symbol = "[◯](bold red)"

[username]
style_user = "#1affc6"
style_root = "white"
format = "[$user@]($style)"
disabled = true
show_always = true

[hostname]
ssh_only = true
format =  "[$hostname ](#1affc6): "

[directory]
style = "yellow"
read_only = ":ro"
read_only_style = "yellow"
truncate_to_repo = false
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
style = "purple"
symbol = " "
format = ": [$symbol$branch]($style) "

[line_break]
disabled = false

[jobs]
symbol = "◇"
threshold = 1

[python]
format = 'via [$virtualenv ]($style)'

