version: '3'
services:
  ubu-dev:
    image: ghillb/devcon:latest
    container_name: devcon
    hostname: dc
    tty: true
    network_mode: host
    volumes:
      - home:/home/dv
      - $HOME/code:/home/dv/code
      - /:/home/host
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - dc:127.0.0.1
volumes:
  home:
