services:
  dev:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: dotfiles-dev:local
    container_name: devcon
    hostname: dc
    stdin_open: true
    tty: true
    working_dir: /home/dv/code
    volumes:
      - type: bind
        source: ${HOME}/code
        target: /home/dv/code
