#!/usr/bin/env ansible-playbook

---
- name: Install packages
  connection: local
  hosts: localhost
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true

  tasks:

    - name: Install pre-requisites
      ansible.builtin.package:
        name:
          - make
          - stow
          - git
        state: present
      tags:
        - pre-requisites

    - name: Install pre-requisites (Ubuntu)
      ansible.builtin.package:
        name:
          - software-properties-common
        state: present
      when: ansible_distribution == 'Ubuntu'
      tags:
        - pre-requisites

    - name: Add neovim-ppa repository
      ansible.builtin.apt_repository:
        repo: ppa:neovim-ppa/unstable
        state: present
      when: ansible_distribution == 'Ubuntu'
      tags:
        - terminal-utilities

    - name: Install terminal-utilities
      ansible.builtin.package:
        name:
          - curl
          - wget
          - rsync
          - neovim
          - tmux
          - tig
          - htop
          - podman
          - ripgrep
          - visidata
          - sshfs
          - nnn
          - jq
          - bat
          - exa
          - gron
          - curl
          - shellcheck
          - dos2unix
          - bash-completion
          - ncdu
          - direnv
          - gcc
          - perl
          - golang
          - pre-commit
          - yamllint
          - ansible-lint
          - zoxide
          - keychain
          - dash
          - git-lfs
        state: present
      tags:
        - terminal-utilities

    - name: Install terminal-utilities (Fedora)
      ansible.builtin.package:
        name:
          - sqlite
          - sqlite-devel
        state: present
      tags:
        - terminal-utilities
      when: ansible_distribution == 'Fedora'

    - name: Install terminal-utilities (Ubuntu)
      ansible.builtin.package:
        name:
          - docker.io
          - docker-compose
          - python3-venv
          - python3-pip
          - python3-dev
          - sqlite3
          - libsqlite3-dev
          - silversearcher-ag
          - inetutils-ping
        state: present
      when: ansible_distribution == 'Ubuntu'
      tags:
        - terminal-utilities

    - name: Install desktop-utilities
      ansible.builtin.package:
        name:
          - sway
          - wl-clipboard  # wl version of xsel
          - fira-code-fonts
          - xdotool  # X only
          - wmctrl  # X only
          - wofi
          - kitty
          - nnn
          - rclone
          - zathura
        state: present
      tags:
        - desktop-utilities

    - name: Install utilities via git
      become: false
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        depth: 1
      loop:
        - repo: https://github.com/junegunn/fzf.git
          dest: ~/.fzf
      tags:
        - desktop-utilities
        - terminal-utilities

- name: Install (user) packages
  connection: local
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get nvm install script
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
        dest: /tmp/nvm.sh
        mode: 0777
      tags:
        - desktop-utilities
        - terminal-utilities

    - name: Install nvm
      command: bash /tmp/nvm.sh
      tags:
        - desktop-utilities
        - terminal-utilities

    - name: Install node
      shell: |
        . $HOME/.nvm/nvm.sh
        nvm install 16
      args:
        executable: /bin/bash
      tags:
        - desktop-utilities
        - terminal-utilities
