vim.env.NVC = vim.env.HOME .. "/.config/nvim"

require("settings")
require("plugins")
require("functions")
require("theme")
require("file_types")
-- TODO: convert to lua
vim.cmd("source $NVC/lua/mappings.vim")

-- plugin configs
require("plugc/treesitter")
require("plugc/codi")
require("plugc/nvim-cmp")
require("plugc/tabout")
require("plugc/trouble")
require("plugc/null_ls")
require("plugc/vsnip")
require("plugc/lsp_signature")
require("plugc/lsp_installer")
require("plugc/todo_comments")
require("plugc/lightspeed")
require("plugc/telescope")
require("plugc/neoterm")
require("plugc/alpha")
require("plugc/bufferline")
require("plugc/lualine")
require("plugc/indent_line")
require("plugc/gitsigns")
require("plugc/diffview")
require("plugc/twilight")
require("plugc/zen_mode")
require("plugc/qf_helper")
require("plugc/autopairs")
require("plugc/nvim-tree")
require("plugc/nnn")
require("plugc/mvvis")
require("plugc/async_tasks")
require("plugc/vimwiki")
require("plugc/text-objects")
